### ISSUE TITLE
collection route is not localized

### ISSUE THREAD

**Issue by tilsammans** [kwi/i18n_routing#39]
According to the documentation, this should work. In config/routes.rb:

```
localized do
  resources :films do
    collection do
      get :all
    end
  end
end
```

The 'all' collection is not localized when I use this YAML:

```
nl:
  routes:
    films:
      as: "bios"
      path_names:
        all: "allemaal"
```

i18n_routing version 0.6.2 with Rails 3.2.9. The 'films' collection itself is localized properly.

How can I localize the collection path?
