### ISSUE TITLE
Rails 3, default language slovenian, nested route, works sometimes

### ISSUE THREAD

**Issue by Krule** [kwi/i18n_routing#9]
This is a weird one, translated routes work (when I look at rake routes), however in case I start server they fail to translate. Then, when I edit the gemfile while server is on, routes start working. If I restart it again they stop until gemfile is edited.

My route looks like:

```
localized do
  resources :nepremicnines do
    collection do
      get :obcino
    end
  end
end
```

And en.yml:

```
en:
  resources:
    nepremicnines: "real_estates"
  path_names:
    obcino: "municipality"
```

Since my production is on Heroku, with it's read-only fs, this is a bit of a problem for me.
